name = "FEMeshes"
uuid = "31a97c39-4297-4167-a13b-672cd448a149"
authors = ["Jean-François Barthélémy"]
version = "0.1.0"

[deps]
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
