name = "FEMeshes"
uuid = "31a97c39-4297-4167-a13b-672cd448a149"
authors = ["Jean-François Barthélémy"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
